name: On-demand build on Windows

on:
  workflow_dispatch:

jobs:    
  windows-build:
    name: Build (windows-latest, MSVC)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build executable
      run: |
        cd build
        cmake -S .. -A x64 -DCMAKE_BUILD_TYPE="Release" -B MSVC
        cmake --build MSVC --target ALL_BUILD --config Release

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: RunPsScript_on_demand_build_executable
        path: ${{ github.workspace }}/build/MSVC/Release/
